### ISSUE TITLE
Erros running  actix-middleware-example

### ISSUE THREAD

**Issue by eagleshine** [casbin-rs/examples#47]
error[E0277]: the trait bound CasbinActor<CachedEnforcer>: Actor is not satisfied
--> actix-middleware-example/src/api/user.rs:34:12
|
34 | actor: web::Data<Addr<CasbinActor<CachedEnforcer>>>,
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait Actor is not implemented for CasbinActor<CachedEnforcer>
|
any ideas on how to fix this?

**Comment by hsluoyz** [comment]
@hackerchai

**Comment by hackerchai** [comment]
@eagleshine  you should use ` actor: web::Data<Addr<CasbinActor<CachedEnforcer>>>,`

**Comment by eagleshine** [comment]
**Looks like the text is changed by github**, corrected as below:
error[E0277]: the trait bound `CasbinActor<CachedEnforcer>: Actor` is not satisfied
  --> actix-middleware-example/src/api/user.rs:34:12
   |
34 |     actor: web::Data<Addr<CasbinActor < CachedEnforcer >>>,
   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `Actor` is not implemented for `CasbinActor<CachedEnforcer>`
   |
   |

**Comment by 0xethsign** [comment]
This issue is still there. Doesn't look like a old dependency problem. I cloned the repo, as is, set up the .env. secret.key and the db, and still this error occurred.
This maybe because `Actor` is not implemented for `CasbinActor<T>` where `T: CachedEnforcer` in actix-casbin

![Screenshot from 2021-06-06 15-59-15](https://user-images.githubusercontent.com/55808717/120921200-32ab6780-c6e0-11eb-8231-5e13d9365f8f.png)

**Comment by 0xethsign** [comment]
> This issue is still there. Doesn't look like a old dependency problem. I cloned the repo, as is, set up the .env. secret.key and the db, and still this error occurred.
> This maybe because `Actor` is not implemented for `CasbinActor<T>` where `T: CachedEnforcer` in actix-casbin
> 
> ![Screenshot from 2021-06-06 15-59-15](https://user-images.githubusercontent.com/55808717/120921200-32ab6780-c6e0-11eb-8231-5e13d9365f8f.png)

@hackerchai can you check this?

**Comment by 0xethsign** [comment]
@eagleshine It is a dependency problem caused by the dependendabot. Because we're still waiting for actix-web 4.x stable, we have to use the old versions of actix-web and actix-rt
use this Cargo.toml - 
```toml
[dependencies]
http = "0.2.1"
actix =  "0.10.0"
actix-web = "3.0.2"
actix-service = "1.0.6"
actix-rt = "1.1.1"
actix-cors = "0.4.0"
futures = "0.3.5"
failure = "0.1.8"
serde = "1.0.116"
serde_derive = "1.0.116"
serde_json = "1.0.57"
derive_more = "0.99.10"
chrono = { version = "0.4.18", features = ["serde"] }
diesel = { version = "1.4.5", features = ["postgres","r2d2", "chrono"] }
diesel_migrations = "1.4.0"
dotenv = "0.15.0"
env_logger = "0.8.1"
log = "0.4.11"
jsonwebtoken = "7.2.0"
bcrypt = "0.9.0"
csv = "1.1.3"
walkdir = "2.3.1"
actix-casbin= {version = "0.4.2", default-features = false, features = [ "runtime-async-std" ]}
actix-casbin-auth = {version = "0.4.4", default-features = false, features = [ "runtime-async-std" ]}
diesel-adapter = { version = "0.8.1", default-features = false, features = ["postgres","runtime-async-std"] }
uuid = {version = "0.8.1", features = ["v4"] }
```
